### ISSUE TITLE
14 UNAVAILABLE: No connection established error 

### ISSUE THREAD

**Issue by aalkhatib9** [bstruct/vscode-bigquery#29]
Hi, 

After authenticating using user log in. I get the error "14 UNAVAILABLE: No connection established error"  

and the explorer fails to load tables. I'm not able to query gcp bq either. 

Hope you can help out with this. Thank you for this awesome feature on VsCode 

![bqv](https://user-images.githubusercontent.com/61369640/189216761-7e501a27-4e4d-4b20-bb5f-4fb13a1e4cbd.JPG)

**Comment by DamiaoCastro** [comment]
Hi @aalkhatib9 , thank you for reaching out. 
Super strange error, never seen it before. 
Can you please confirm that the problem persisted after you restarted vs code?
Thank you.

**Comment by aalkhatib9** [comment]
> Hi @aalkhatib9 , thank you for reaching out. Super strange error, never seen it before. Can you please confirm that the problem persisted after you restarted vs code? Thank you.

Hey, unfortunately it continues to happen after restarting. Just tried multiple times from different computers.

**Comment by DamiaoCastro** [comment]
@aalkhatib9 , just released a new version - 0.0.11 - that aims to give more visibility on the gcloud commands that are triggered to support the authentication. Hopefully this will give more visibility on this issue. 
Thank you

**Comment by aalkhatib9** [comment]
@DamiaoCastro 
Sorry for coming back late to this but thought I'd give you an update. I think this error has to do with working behind my company's proxy. 

Strange enough however, I am able to query the tables using the extension however the explorer returns "14 UNAVAILABLE: No connection established error #29." 

Is there a way in the extension to configure the proxy settings for the explorer or for it to import the proxy variables from environment variables? If not, can I request it as a new feature request/enhancement? 

Again, thank you for this awesome extension.

**Comment by DamiaoCastro** [comment]
Hi @aalkhatib9 . Your problem is quite interesting, and hopefully not common. I assume that you can run queries fine from the GCP console, because there would be no direct communication with the bigquery URL. 
For sure I would like to implement this functionality. 
I will re-open this issue. Any information that you can give me about that proxy setup will be extremely valuable. 
At the moment I'm restructuring the internals of the extension, so that it becomes easier to test. 
I will implement login and connectivity features right after.
Thank you

**Comment by aalkhatib9** [comment]
Thank you @DamiaoCastro 

You're right, I can run queries fine in the GCP console. In command prompt too like bq sql, bq load, etc... 
I'm trying to get you more info about our proxy environment but there's only so much info I can gather. Most I can say is that it uses a proxy script through Mcafee. I hope this helps. 

Thanks again.

**Comment by aalkhatib9** [comment]
@DamiaoCastro 
Also, please let me know if there's anything else I can do to help.

**Comment by DamiaoCastro** [comment]
Hi @aalkhatib9 . I've been looking into this topic and there's 2 important things to notice.
- vs code does allow proxy configuration - https://docs.mend.io/en-US/bundle/wsk/page/how_to_set_up_proxy_settings_for_advise_for_visual_studio_code.html
- The bigquery client that is provided by google, doesn't accept any proxy parameter, but I can provide a different endpoint.

I don't know, if by setting a proxy in visual studio code, all internal communication is automatically routed there. And if it is, we might see a different behavior from the extension vs the command line inside vs code. ( the proxy for vs code might not cover the command line )

Can you please try to setup the proxy a see if you have a different error or different behavior?
If not, I can try to leverage that different endpoint that the Bigquery client allows me to configure.
Thank you.

**Comment by DamiaoCastro** [comment]
Hi @aalkhatib9 , very happy to hear that now you're able to use BQ inside vs code. Any suggestion for improvement of the extension, please let me know. Thank you.
