### ISSUE TITLE
GCP project favorites and/or filter 

### ISSUE THREAD

**Issue by sivaiahnaidu** [bstruct/vscode-bigquery#31]
If a person was assigned several projects assigned to them the list of projects can became big. So, a feature like favourites or a filter will make resolve this issue. 

PS: Props to you. great work on the extension

**Comment by DamiaoCastro** [comment]
Hi @sivaiahnaidu , thank you for reaching out. Agree. Let me see what is the best option for this. Ideally I would like to persist some information with the VS Code user authentication. I will check.
