### ISSUE TITLE
Syntax check applied on all file type

### ISSUE THREAD

**Issue by dariodimarzo** [bstruct/vscode-bigquery#34]
The syntax check is currently applied on all file types.
This is inconvenient since some errors are highlighted on various file type (e.g. all the from clause importing packages in Python are highlighted as error).

The syntax check should be applied on sql bigquery files only.

**Comment by DamiaoCastro** [comment]
Hi @dariodimarzo , thank you for this. Will confirm and fix this in the next 2 days.

**Comment by DamiaoCastro** [comment]
Hi @dariodimarzo . Just published a new version of the extension. Please let me know if your problem is now solved.
Thank you

**Comment by dariodimarzo** [comment]
Hi @DamiaoCastro, problem fixed.

Thanks a lot!
