### ISSUE TITLE
Extension is missing in OpenVSX repository

### ISSUE THREAD

**Issue by mar-pan** [bstruct/vscode-bigquery#49]
Hello, I'm loving your extension functionalities however it's missing in Open VSX repository (Code OSS default one). For now, I was able to make it work by manual installation but is there a possibility that you could push it there? I found a [script](https://github.com/open-vsx/publish-extensions) on how to do that.

**Comment by DamiaoCastro** [comment]
Hi @mar-pan , thank you for pointing this out to me. Just uploaded the extension there. 
In my personal computer I use Pop Os, and I just installed "Code - OSS" via the app installer that seems to put applications in some type of container. Therefore I'm having issues using the underlying `gcloud` functionality for authentication. I will try to figure it out later during the week.
Can I ask you what is your setup? So I can understand if there's further improvements and tests that need to be planned.
Thank you

**Comment by mar-pan** [comment]
I'm using it in Cloud Workstations - new GCP offerings and there is Code-Oss installed and I've noticed that when there is auth option initialised from your extension it starts with quiet flag, therefore I'm unable to login because I need to pass authorization code from a browser (as this is the only auth option supported there) So to make it work gcloud should start without --quiet when run from CodeOSS

**Comment by mar-pan** [comment]
Hey @DamiaoCastro kind ping there

**Comment by DamiaoCastro** [comment]
Hi @mar-pan . I added the extension here: https://open-vsx.org/extension/bstruct/vscode-bigquery 
Sorry, forgot to update you. Still get the message of "namespace not verified". I will try to fix that now.
