### ISSUE TITLE
Adding projects to the Explorer view

### ISSUE THREAD

**Issue by stefanavesand** [bstruct/vscode-bigquery#51]
Thank you for a great extension!

It would be really helpful to be able to add projects to the Explorer view.
Now it only shows projects where the active account has Owner, Editor, Browser or Viewer permissions on project level.
Since BigQuery also supports permissions on dataset and table level this means that a lot of projects are missing.
One way to work around this issue would be to allow the user to manually add projects, datasets of tables that should be visible in the Explorer view.

Best regards,
Stefan

**Comment by DamiaoCastro** [comment]
Hi @stefanavesand , thank you for point this out. Let me figure out what is the best tactic to do this regarding the API's that can be leveraged to do this.

**Comment by DamiaoCastro** [comment]
Hi @stefanavesand , the possibility of adding projects to the explorer is done in the new version 0.1.0. Also noticed that when the permissions are only given to a table, the project configuration would not be enough. So I also added the option to configure a table.
https://github.com/bstruct/vscode-bigquery/tree/0.1.0#settings
Please let me know if this documentation is not enough to understand how it works and also please let me know if you bump into another issue.
