### ISSUE TITLE
Extension (v0.1.1) doesn't start in Code-OSS - telemetry issue

### ISSUE THREAD

**Issue by k-lawecki** [bstruct/vscode-bigquery#55]
I just updated the extension to v.0.1.1 code-oss; the extension doesn't work, see below from from the logs:

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/112689442/224548275-203fb623-5a97-4d68-a613-9a0051af91cc.png">

**Comment by DamiaoCastro** [comment]
@k-lawecki , just released version 0.1.2 where I lower the version of the telemetry package to the version that was before. Hopefully this will help to mitigate the problem that you raised.
Please keep me updated.

**Comment by k-lawecki** [comment]
Hey @DamiaoCastro 
I'm using it on GCP Workstations;
just tested 0.1.2 (thanks for such quick reaction), but this time getting following error:
<img width="1194" alt="image" src="https://user-images.githubusercontent.com/112689442/224632855-53d1fc7c-e488-46a4-9107-8fa6a9fd363e.png">

**Comment by DamiaoCastro** [comment]
Sorry for this messy release and thank you for the explicit error message, it did help to pin point the issue. Hopefully there will be no more problems in this new version. 
https://open-vsx.org/extension/bstruct/vscode-bigquery/0.1.21

**Comment by k-lawecki** [comment]
It works properly now - thank you for the really fast reaction & excellent extension! :)
