### ISSUE TITLE
Enhancement Request - Routines/Stored Procedures

### ISSUE THREAD

**Issue by aalkhatib9** [bstruct/vscode-bigquery#57]
Hello,

A great nice to have feature would be the ability to open up the stored procedure using the extension and viewing the code behind it. Same for Views. 

It can currently be done by querying 
SELECT      ddl
FROM       dataset.information_schema.routines
WHERE     rooutine_name = 'name of stored procedure'; 

But to have the option to right click and open/edit the stored procedure would be an awesome feature. Thank you.

**Comment by DamiaoCastro** [comment]
Hi @aalkhatib9 , thank you for reaching out and the pointer that you already gave me.
I will put this feature in the next release.
Update you as soon as is done.

**Comment by DamiaoCastro** [comment]
Hi @aalkhatib9 , when possible, can you try the latest version to confirm that the DDL feature that you requested is working as expected?
Thank you.

**Comment by aalkhatib9** [comment]
Just tried it out, I see you added it to tables too! thank you so much for that! This is awesome!
